# --- Stage 1: build the React frontend ---
FROM node:22-alpine AS web
WORKDIR /web
COPY web/package.json web/package-lock.json* ./
RUN npm install
COPY web/ ./
RUN npm run build

# --- Stage 2: runtime (Express API + static frontend) ---
FROM node:22-alpine AS runtime
WORKDIR /app

# native deps for better-sqlite3
RUN apk add --no-cache python3 make g++

COPY server/package.json server/package-lock.json* ./server/
RUN cd server && npm install --omit=dev

# app code
COPY server/ ./server/
COPY --from=web /web/dist ./web/dist

# seed data (generated by scripts/import-excel.js, committed to the repo)
# server/data/seed.json is included via the COPY server/ above.

ENV NODE_ENV=production
ENV PORT=3000
EXPOSE 3000

WORKDIR /app/server
CMD ["node", "src/index.js"]
